components:
  schemas:
    BlogPost:
      description: a blog post
      properties:
        author:
          title: Author
          type: string
        content:
          title: Content
          type: string
        published:
          format: date-time
          title: Published
          type: string
        title:
          title: Title
          type: string
      required:
      - title
      - author
      - content
      - published
      title: BlogPost
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Response_List_server.api.BlogPost__:
      description: a generic api response
      properties:
        data:
          items:
            $ref: '#/components/schemas/BlogPost'
          title: Data
          type: array
        errors:
          items:
            type: string
          title: Errors
          type: array
      required:
      - data
      title: Response[List[server.api.BlogPost]]
      type: object
    Response_str_:
      description: a generic api response
      properties:
        data:
          title: Data
          type: string
        errors:
          items:
            type: string
          title: Errors
          type: array
      required:
      - data
      title: Response[str]
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /api/blog/posts:
    get:
      description: Serve up some _original content_
      operationId: get_blog_posts_api_blog_posts_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_List_server.api.BlogPost__'
          description: Successful Response
      summary: Get Blog Posts
  /api/greeting:
    get:
      description: say hello
      operationId: greet_api_greeting_get
      parameters:
      - in: query
        name: to_greet
        required: true
        schema:
          title: To Greet
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_str_'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Greet

