/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * a blog post
 * @export
 * @interface BlogPost
 */
export interface BlogPost {
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof BlogPost
     */
    published: Date;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    title: string;
}

/**
 * Check if a given object implements the BlogPost interface.
 */
export function instanceOfBlogPost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "author" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "published" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function BlogPostFromJSON(json: any): BlogPost {
    return BlogPostFromJSONTyped(json, false);
}

export function BlogPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': json['author'],
        'content': json['content'],
        'published': (new Date(json['published'])),
        'title': json['title'],
    };
}

export function BlogPostToJSON(value?: BlogPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'content': value.content,
        'published': (value.published.toISOString()),
        'title': value.title,
    };
}

