/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * a generic api response
 * @export
 * @interface ResponseStr
 */
export interface ResponseStr {
    /**
     * 
     * @type {string}
     * @memberof ResponseStr
     */
    data: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseStr
     */
    errors?: Array<string>;
}

/**
 * Check if a given object implements the ResponseStr interface.
 */
export function instanceOfResponseStr(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ResponseStrFromJSON(json: any): ResponseStr {
    return ResponseStrFromJSONTyped(json, false);
}

export function ResponseStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseStr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function ResponseStrToJSON(value?: ResponseStr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'errors': value.errors,
    };
}

